name: ecAssemble
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - bedtools=2.31.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.11.17
  - flye=2.9.3
  - htslib=1.17
  - k8=0.2.5
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.1.2
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - libnghttp2=1.52.0
  - libopenblas=0.3.25
  - libsqlite=3.44.2
  - libssh2=1.11.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - minimap2=2.26
  - ncurses=6.4
  - numpy=1.26.2
  - openssl=3.2.0
  - pandas=2.1.4
  - pip=23.3.2
  - pysam=0.21.0
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3.post1
  - readline=8.2
  - setuptools=68.2.2
  - six=1.16.0
  - tk=8.6.13
  - tzdata=2023c
  - wheel=0.42.0
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
